services:
  caddy:
    build:
      context: ..
      dockerfile: docker/caddy/Dockerfile
    network_mode: host
    restart: unless-stopped
    volumes:
      - ../caddy-example/Caddyfile:/etc/caddy/Caddyfile
      - ../caddy-example/public:/public
      - caddy-data:/data
      - caddy-config:/config

  proxy:
    build:
      context: ..
      dockerfile: docker/proxy/Dockerfile
    network_mode: host
    restart: unless-stopped
    environment:
      - PORT=3000

volumes:
  caddy-data:
  caddy-config:
